version: 1.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplicationStop:
    - location: srcipts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: srcipts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user